# Generated by Django 6.0.7 on 2026-08-02 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Bio professionnelle'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_slots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'ids : coiffure, esthetique, barbier, nail", verbose_name='Spécialités'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espace', models.CharField(max_length=8, verbose_name='Espace (137/80)')),
                ('poste', models.CharField(max_length=64, verbose_name='Libellé poste')),
                ('poste_id', models.CharField(blank=True, default='', max_length=64)),
                ('type_poste', models.CharField(max_length=32, verbose_name='Type')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('en_cours', 'En cours')], default='a_venir', max_length=16)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('service_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
